#!/usr/bin/env bash

USER=$(whoami)

USERNAME_FILE=/etc/nixos/username.json
USERNAME_FILE_ORI=./secrets/nixos/username.json
if [[ ! -f "$USERNAME_FILE" ]]; then
    sudo cp -Rf $USERNAME_FILE_ORI $USERNAME_FILE
    sudo sed -i 's/\"defaultUser\": \"\"/\"defaultUser\": \"'${USER}'\"/' "$USERNAME_FILE"
fi

SECRETS_FILE_DIR="/home/${USER}/.config/nixos"
SECRETS_FILE="${SECRETS_FILE_DIR}/secrets.json"
SECRETS_FILE_ORI="./secrets/nixos/secrets.json"
if [[ ! -f "$SECRETS_FILE" ]]; then
    mkdir -p $SECRETS_FILE_DIR
    sudo cp -Rf $SECRETS_FILE_ORI $SECRETS_FILE
    sudo chmod 600 $SECRETS_FILE
fi

PROJECT_DIR="/home/${USER}/projects"
NOTES_FILE_DIR="/home/${USER}/notes"
if [[ $1 == "work" ]]; then
    PROJECT_DIR="/home/${USER}/work/projects"
    NOTES_FILE_DIR="/home/${USER}/work/notes"
fi

if [[ ! -f "$PROJECT_DIR" ]]; then
    mkdir -p $PROJECT_DIR
fi

NOTES_FILE="${NOTES_FILE_DIR}/notes.txt"
if [[ ! -f "$NOTES_FILE" ]]; then
    mkdir -p $NOTES_FILE_DIR
    touch $NOTES_FILE
fi

DIRENV_FILE="/home/$USER/.direnvrc"
if [[ ! -f "$DIRENV_FILE" ]]; then
    echo "source /run/current-system/sw/share/nix-direnv/direnvrc" > $DIRENV_FILE
fi

# rm -f flake.lock
# nix-collect-garbage
sudo nix-channel --update
sudo nixos-rebuild switch --flake ./#$1 --impure
