#!/usr/bin/env bash

USER=$(whoami)

USERNAME_FILE=/etc/nixos/username.json
USERNAME_FILE_ORI=./secrets/nixos/username.json

if [[ ! -f "$USERNAME_FILE" ]]; then
    sudo cp -Rf $USERNAME_FILE_ORI $USERNAME_FILE
    sudo sed -i 's/\"defaultUser\": \"\"/\"defaultUser\": \"'${USER}'\"/' "$USERNAME_FILE"
fi

SECRETS_FILE_DIR="/home/${USER}/.config/nixos"
SECRETS_FILE="${SECRETS_FILE_DIR}/secrets.json"
SECRETS_FILE_ORI="./secrets/nixos/secrets.json"

if [[ ! -f "$SECRETS_FILE" ]]; then
    mkdir -p $SECRETS_FILE_DIR
    sudo cp -Rf $SECRETS_FILE_ORI $SECRETS_FILE
    sudo chmod 600 $SECRETS_FILE
fi

NOTES_FILE_DIR="/home/${USER}/notes"
NOTES_FILE="${NOTES_FILE_DIR}/notes.txt"

if [[ ! -f "$NOTES_FILE" ]]; then
    mkdir -p $NOTES_FILE_DIR
    touch $NOTES_FILE
fi


# CONFIG=./configuration.nix
# CONFIG_ORI=/etc/nixos/configuration.nix

# HARDWARE=./hardware-configuration.nix
# HARDWARE_ORI=/etc/nixos/hardware-configuration.nix

# if [[ ! -f "$CONFIG" ]]; then
#     cp $CONFIG_ORI .
# fi

# if [[ ! -f "$HARDWARE" ]]; then
#     cp $HARDWARE_ORI .
# fi

# sed -i '/users.users.*$/,/};/d' "$CONFIG"

# rm -f flake.lock
# nix-collect-garbage
sudo nixos-rebuild switch --flake ./#$1 --impure
